# DO NOT EDIT THIS FILE

SUBMIT  := $(wildcard src/main/java/org/cis120/*.java src/test/java/org/cis120/*.java PLAN.txt)

EXCLUDE := \
	src/main/java/org/cis120/Broadcast.java \
	src/main/java/org/cis120/Command.java \
	src/main/java/org/cis120/CommandParser.java \
	src/main/java/org/cis120/ServerBackend.java \
	src/main/java/org/cis120/ServerResponse.java \
	src/main/java/org/cis120/ServerMain.java \
	src/main/java/org/cis120/ServerModelApi.java \
	src/test/java/org/cis120/Task2Test.java \
	src/test/java/org/cis120/Task4Test.java \
	src/test/java/org/cis120/Task3Test.java \
	src/test/java/org/cis120/Task5Test.java

SUBMIT  := $(filter-out $(EXCLUDE),$(SUBMIT))

HWNAME := hw07
ts := $(shell /bin/date "+%Y-%m-%d-%H:%M:%S")

ZIPNAME := $(HWNAME)-submit($(ts)).zip

.PHONY: all compile run zip test checkstyle format clean

all:	

compile:
	mvn compile

run: compile
	mvn exec:java

zip: $(SUBMIT)
	zip -j '$(ZIPNAME)' $(SUBMIT)

test: 
	mvn test

test-stack-trace:
	mvn -DtrimStackTrace=false test

checkstyle: 
	mvn checkstyle:checkstyle

format:
	mvn formatter:format

clean:
	rm -f src/*.class bin/* test/*.class
	rm -rf *.zip
	mvn clean
